module.exports = function (keyboardNumber) {
  return [
    '<center class="wrapper" style="display: table;table-layout: fixed;width: 100%;min-width: 620px;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;background-color: #fbfbfb;">',
    '<table class="gmail" style="border-collapse: collapse;border-spacing: 0;width: 650px;min-width: 650px;"><tbody><tr><td style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;">&nbsp;</td></tr></tbody></table>',
    '<table class="preheader centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;">',
    "<tbody><tr>",
    '<td style="padding: 0;vertical-align: top;">',
    '<table style="border-collapse: collapse;border-spacing: 0;width: 602px;">',
    "<tbody><tr>",
    '<td class="title" style="padding: 0;vertical-align: top;font-family: Georgia,serif;color: #999;padding-top: 10px;padding-bottom: 12px;font-size: 12px;line-height: 21px;text-align: left;">',
    "&nbsp;",
    "</td>",
    "</tr>",
    "</tbody></table>",
    "</td>",
    "</tr>",
    "</tbody></table>",
    '<table class="header centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 602px;">',
    '<tbody><tr><td class="logo emb-logo-padding-box" style="padding: 0;vertical-align: top;mso-line-height-rule: at-least;padding-top: 0px;padding-bottom: 21px;"><div class="logo-left" style="font-family: Avenir,sans-serif;color: #41637e;font-weight: 700;letter-spacing: -0.02em;font-size: 26px !important;line-height: 32px !important;" align="left" id="emb-email-header">나도 살래 키보드</div></td></tr>',
    "</tbody></table>",
    '<table class="centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;">',
    "<tbody><tr>",
    '<td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #e9e9e9;width: 1px;">&#8203;</td>',
    '<td style="padding: 0;vertical-align: top;">',
    '<table class="one-col" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #00a6de;font-size: 14px;table-layout: fixed;">',
    "<tbody><tr>",
    '<td class="column" style="padding: 0;vertical-align: top;text-align: left;">',
    '<div><div class="column-top" style="font-size: 32px;line-height: 32px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;">&nbsp;</div></div>',
    '<table class="contents" style="border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;">',
    "<tbody><tr>",
    '<td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;">',
    '<h1 class="size-28" style="font-style: normal;font-weight: 700;Margin-bottom: 0;Margin-top: 0;font-size: 24px;line-height: 36px;font-family: sans-serif;color: #cf61cf;"><span style="color:#fbfbfb">키보드가 입고 되었어요.</span></h1>',
    '<p class="font-roboto" style="font-style: normal;font-weight: 400;font-family: roboto,tahoma,sans-serif;Margin-bottom: 0;Margin-top: 18px;line-height: 24px;color: #565656;font-size: 16px;">',
    '<span style="color:#ffffff">😁</span></p>',
    '<p style="font-style: normal;font-weight: 400;Margin-bottom: 0;Margin-top: 24px;line-height: 24px;font-family: Georgia,serif;color: #565656;font-size: 16px;">&nbsp;</p><p style="font-style: normal;font-weight: 400;Margin-bottom: 24px;Margin-top: 24px;line-height: 24px;font-family: Georgia,serif;color: #565656;font-size: 16px;">&nbsp;</p>',
    "</td>",
    "</tr>",
    "</tbody></table>",
    '<table class="contents" style="border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;">',
    "<tbody><tr>",
    '<td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;">',
    '<div class="btn" style="Margin-bottom: 0;Margin-top: 0;text-align: center;">',
    `<![if !mso]><a style="border-radius: 3px;display: inline-block;font-size: 14px;font-weight: 700;line-height: 24px;padding: 13px 35px 12px 35px;text-align: center;text-decoration: none !important;transition: opacity 0.2s ease-in;color: #fff;background-color: #2b5578;" href="https://www.leopold.co.kr/Shop/Item.php?ItId=${keyboardNumber}" target="_blank" data-width="119">사러 가기</a><![endif]>`,
    "</td>",
    "</tr>",
    "</tbody></table>",
    '<div class="column-bottom" style="font-size: 32px;line-height: 32px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;">&nbsp;</div>',
    "</td>",
    "</tr>",
    "</tbody></table>",
    "</td>",
    '<td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #e9e9e9;width: 1px;">&#8203;</td>',
    "</tr>",
    "</tbody></table>",
    '<table class="border" style="border-collapse: collapse;border-spacing: 0;font-size: 1px;line-height: 1px;background-color: #e9e9e9;Margin-left: auto;Margin-right: auto;" width="602">',
    '<tbody><tr class="border" style="font-size: 1px;line-height: 1px;background-color: #e9e9e9;height: 1px;">',
    '<td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #e9e9e9;width: 1px;">&#8203;</td>',
    '<td style="padding: 0;vertical-align: top;line-height: 1px;">&#8203;</td>',
    '<td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #e9e9e9;width: 1px;">&#8203;</td>',
    "</tr>",
    "</tbody></table>",
    '<table class="centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;">',
    "<tbody><tr>",
    '<td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #e9e9e9;width: 1px;">&#8203;</td>',
    '<td style="padding: 0;vertical-align: top;">',
    '<table class="one-col" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 600px;background-color: #ffffff;font-size: 14px;table-layout: fixed;" emb-background-style>',
    "<tbody><tr>",
    '<td class="column" style="padding: 0;vertical-align: top;text-align: left;">',
    '<div><div class="column-top" style="font-size: 32px;line-height: 32px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;">&nbsp;</div></div>',
    '<table class="contents" style="border-collapse: collapse;border-spacing: 0;table-layout: fixed;width: 100%;">',
    "<tbody><tr>",
    '<td class="padded" style="padding: 0;vertical-align: top;padding-left: 32px;padding-right: 32px;word-break: break-word;word-wrap: break-word;">',
    '<p class="size-12" style="font-style: normal;font-weight: 400;Margin-bottom: 0;Margin-top: 0;line-height: 19px;color: #565656;font-size: 12px;text-align: center;"><span style="color:rgb(153, 153, 153)">https://github.com/seungdeng17/sold-out-keyboard</span></p>',
    "</td>",
    "</tr>",
    "</tbody></table>",
    '<div class="column-bottom" style="font-size: 32px;line-height: 32px;transition-timing-function: cubic-bezier(0, 0, 0.2, 1);transition-duration: 150ms;transition-property: all;">&nbsp;</div>',
    "</td>",
    "</tr>",
    "</tbody></table>",
    "</td>",
    '<td class="border" style="padding: 0;vertical-align: top;font-size: 1px;line-height: 1px;background-color: #e9e9e9;width: 1px;">&#8203;</td>',
    "</tr>",
    "</tbody>",
    "</table>",
    '<table class="border" style="border-collapse: collapse;border-spacing: 0;font-size: 1px;line-height: 1px;background-color: #e9e9e9;Margin-left: auto;Margin-right: auto;" width="602">',
    '<tbody><tr><td style="padding: 0;vertical-align: top;">&#8203;</td></tr></tbody>',
    "</table>",
    '<table class="footer centered" style="border-collapse: collapse;border-spacing: 0;Margin-left: auto;Margin-right: auto;width: 100%;">',
    "<tbody><tr>",
    '<td style="padding: 0;vertical-align: top;">&nbsp;</td>',
    '<td class="inner" style="padding: 58px 0 29px 0;vertical-align: top;width: 600px;">',
    '<table class="right" style="border-collapse: collapse;border-spacing: 0;" align="right">',
    "<tbody><tr>",
    '<td style="padding: 0;vertical-align: top;color: #999;font-size: 12px;line-height: 22px;max-width: 200px;mso-line-height-rule: at-least;">',
    "</td>",
    "</tr>",
    "</tbody></table>",
    "</td>",
    "</tr>",
    "</tbody></table>",
    "</center>",
  ].join("\n");
};
